name: Test-CodeBuild

on: [pull_request, push]

jobs:
  run-codebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ASIA53MMGTC7BDP7ZLCX
          aws-secret-access-key: Dyrb4VgzOn9lXFtHS1rYd1PE34glg2bF/qhRAxeu
          aws-region: us-west-2
      - name: Run CodeBuild
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: aws-codebuild-run-build-test
